import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  {
    name: "India",
    officialName: "Republic of India",
    population: 1417492000,
    alias: ["IND", "Bharat", "Republic of India"],
  },
  {
    name: "China",
    officialName: "People's Republic of China",
    population: 1408280000,
    alias: ["CN", "PRC", "Zhongguo", "People's Republic of China"],
  },
  {
    name: "United States",
    officialName: "United States of America",
    population: 340110988,
    alias: [
      "USA",
      "US",
      "United States of America",
      "America",
      "U.S.A.",
      "U.S.",
    ],
  },
  {
    name: "Indonesia",
    officialName: "Republic of Indonesia",
    population: 284438782,
    alias: ["IDN", "Republic of Indonesia"],
  },
  {
    name: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
    population: 241499431,
    alias: ["PAK", "Islamic Republic of Pakistan"],
  },
  {
    name: "Nigeria",
    officialName: "Federal Republic of Nigeria",
    population: 223800000,
    alias: ["NGA", "Federal Republic of Nigeria"],
  },
  {
    name: "Brazil",
    officialName: "Federative Republic of Brazil",
    population: 213421037,
    alias: ["BRA", "Brasil", "Federative Republic of Brazil"],
  },
  {
    name: "Bangladesh",
    officialName: "People's Republic of Bangladesh",
    population: 169828911,
    alias: ["BGD", "People's Republic of Bangladesh"],
  },
  {
    name: "Russia",
    officialName: "Russian Federation",
    population: 146028325,
    alias: ["RUS", "Russian Federation", "Россия"],
  },
  {
    name: "Mexico",
    officialName: "United Mexican States",
    population: 130575786,
    alias: ["MEX", "México", "United Mexican States"],
  },
  {
    name: "Japan",
    officialName: "Japan",
    population: 123210000,
    alias: ["JPN", "Nihon", "Nippon", "日本"],
  },
  {
    name: "Philippines",
    officialName: "Republic of the Philippines",
    population: 114123600,
    alias: ["PHL", "Pilipinas", "Republic of the Philippines"],
  },
  {
    name: "DR Congo",
    officialName: "Democratic Republic of the Congo",
    population: 112832000,
    alias: [
      "COD",
      "DRC",
      "Congo-Kinshasa",
      "Democratic Republic of the Congo",
      "Zaire",
    ],
  },
  {
    name: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
    population: 111652998,
    alias: ["ETH", "Abyssinia", "Federal Democratic Republic of Ethiopia"],
  },
  {
    name: "Egypt",
    officialName: "Arab Republic of Egypt",
    population: 107271260,
    alias: ["EGY", "Arab Republic of Egypt", "Misr"],
  },
  {
    name: "Vietnam",
    officialName: "Socialist Republic of Vietnam",
    population: 101343800,
    alias: ["VNM", "Viet Nam", "Socialist Republic of Vietnam"],
  },
  {
    name: "Iran",
    officialName: "Islamic Republic of Iran",
    population: 85961000,
    alias: ["IRN", "Persia", "Islamic Republic of Iran"],
  },
  {
    name: "Turkey",
    officialName: "Republic of Turkey",
    population: 85664944,
    alias: ["TUR", "Türkiye", "Republic of Turkey"],
  },
  {
    name: "Germany",
    officialName: "Federal Republic of Germany",
    population: 83491249,
    alias: ["DEU", "Deutschland", "Federal Republic of Germany"],
  },
  {
    name: "United Kingdom",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
    population: 69281437,
    alias: [
      "UK",
      "GB",
      "GBR",
      "Great Britain",
      "Britain",
      "England",
      "United Kingdom of Great Britain and Northern Ireland",
    ],
  },
  {
    name: "Tanzania",
    officialName: "United Republic of Tanzania",
    population: 68153004,
    alias: ["TZA", "United Republic of Tanzania"],
  },
  {
    name: "France",
    officialName: "French Republic",
    population: 66351959,
    alias: ["FRA", "French Republic", "République française"],
  },
  {
    name: "Thailand",
    officialName: "Kingdom of Thailand",
    population: 65859640,
    alias: ["THA", "Siam", "Kingdom of Thailand"],
  },
  {
    name: "South Africa",
    officialName: "Republic of South Africa",
    population: 63100945,
    alias: ["ZAF", "RSA", "Republic of South Africa"],
  },
  {
    name: "Italy",
    officialName: "Italian Republic",
    population: 58927633,
    alias: ["ITA", "Italia", "Italian Republic"],
  },
  {
    name: "Kenya",
    officialName: "Republic of Kenya",
    population: 53330978,
    alias: ["KEN", "Republic of Kenya"],
  },
  {
    name: "Colombia",
    officialName: "Republic of Colombia",
    population: 53057212,
    alias: ["COL", "Republic of Colombia"],
  },
  {
    name: "Sudan",
    officialName: "Republic of the Sudan",
    population: 51662000,
    alias: ["SDN", "Republic of the Sudan"],
  },
  {
    name: "Myanmar",
    officialName: "Republic of the Union of Myanmar",
    population: 51316756,
    alias: ["MMR", "Burma", "Republic of the Union of Myanmar"],
  },
  {
    name: "South Korea",
    officialName: "Republic of Korea",
    population: 51159889,
    alias: ["KOR", "Korea", "Republic of Korea", "한국"],
  },
  {
    name: "Spain",
    officialName: "Kingdom of Spain",
    population: 49315949,
    alias: ["ESP", "España", "Kingdom of Spain"],
  },
  {
    name: "Algeria",
    officialName: "People's Democratic Republic of Algeria",
    population: 47400000,
    alias: ["DZA", "People's Democratic Republic of Algeria", "Al-Jazā'ir"],
  },
  {
    name: "Argentina",
    officialName: "Argentine Republic",
    population: 46735004,
    alias: ["ARG", "Argentine Republic"],
  },
  {
    name: "Iraq",
    officialName: "Republic of Iraq",
    population: 46118793,
    alias: ["IRQ", "Republic of Iraq"],
  },
  {
    name: "Uganda",
    officialName: "Republic of Uganda",
    population: 45905417,
    alias: ["UGA", "Republic of Uganda"],
  },
  {
    name: "Afghanistan",
    officialName: "Islamic Republic of Afghanistan",
    population: 43844000,
    alias: ["AFG", "Islamic Republic of Afghanistan"],
  },
  {
    name: "Canada",
    officialName: "Canada",
    population: 41651653,
    alias: ["CAN", "CA"],
  },
  {
    name: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
    population: 37859698,
    alias: ["UZB", "Republic of Uzbekistan"],
  },
  {
    name: "Poland",
    officialName: "Republic of Poland",
    population: 37392000,
    alias: ["POL", "Polska", "Republic of Poland"],
  },
  {
    name: "Morocco",
    officialName: "Kingdom of Morocco",
    population: 36828330,
    alias: ["MAR", "Al-Maghrib", "Kingdom of Morocco"],
  },
  {
    name: "Angola",
    officialName: "Republic of Angola",
    population: 36170961,
    alias: ["AGO", "Republic of Angola"],
  },
  {
    name: "Saudi Arabia",
    officialName: "Kingdom of Saudi Arabia",
    population: 35300280,
    alias: ["SAU", "KSA", "Kingdom of Saudi Arabia"],
  },
  {
    name: "Peru",
    officialName: "Republic of Peru",
    population: 34350244,
    alias: ["PER", "Republic of Peru"],
  },
  {
    name: "Malaysia",
    officialName: "Malaysia",
    population: 34231700,
    alias: ["MYS", "MY"],
  },
  {
    name: "Mozambique",
    officialName: "Republic of Mozambique",
    population: 34090466,
    alias: ["MOZ", "Republic of Mozambique"],
  },
  {
    name: "Ghana",
    officialName: "Republic of Ghana",
    population: 33742380,
    alias: ["GHA", "Republic of Ghana", "Gold Coast"],
  },
  {
    name: "Ukraine",
    officialName: "Ukraine",
    population: 32862000,
    alias: ["UKR", "Україна"],
  },
  {
    name: "Yemen",
    officialName: "Republic of Yemen",
    population: 32684503,
    alias: ["YEM", "Republic of Yemen"],
  },
  {
    name: "Madagascar",
    officialName: "Republic of Madagascar",
    population: 31727042,
    alias: ["MDG", "Republic of Madagascar"],
  },
  {
    name: "Ivory Coast",
    officialName: "Republic of Côte d'Ivoire",
    population: 31719275,
    alias: ["CIV", "Côte d'Ivoire", "Republic of Côte d'Ivoire"],
  },
  {
    name: "Nepal",
    officialName: "Federal Democratic Republic of Nepal",
    population: 29911840,
    alias: ["NPL", "Federal Democratic Republic of Nepal"],
  },
  {
    name: "Cameroon",
    officialName: "Republic of Cameroon",
    population: 29442327,
    alias: ["CMR", "Republic of Cameroon"],
  },
  {
    name: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
    population: 28517000,
    alias: ["VEN", "Bolivarian Republic of Venezuela"],
  },
  {
    name: "Australia",
    officialName: "Commonwealth of Australia",
    population: 27536874,
    alias: ["AUS", "AU", "Commonwealth of Australia", "Oz"],
  },
  {
    name: "Niger",
    officialName: "Republic of Niger",
    population: 26312034,
    alias: ["NER", "Republic of Niger"],
  },
  {
    name: "North Korea",
    officialName: "Democratic People's Republic of Korea",
    population: 25950000,
    alias: ["PRK", "DPRK", "Democratic People's Republic of Korea"],
  },
  {
    name: "Syria",
    officialName: "Syrian Arab Republic",
    population: 25620000,
    alias: ["SYR", "Syrian Arab Republic"],
  },
  {
    name: "Burkina Faso",
    officialName: "Burkina Faso",
    population: 24070553,
    alias: ["BFA", "Upper Volta"],
  },
  {
    name: "Taiwan",
    officialName: "Republic of China (Taiwan)",
    population: 23317031,
    alias: ["TWN", "ROC", "Republic of China", "Formosa"],
  },
  {
    name: "Mali",
    officialName: "Republic of Mali",
    population: 22395489,
    alias: ["MLI", "Republic of Mali"],
  },
  {
    name: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
    population: 21763170,
    alias: ["LKA", "Ceylon", "Democratic Socialist Republic of Sri Lanka"],
  },
  {
    name: "Malawi",
    officialName: "Republic of Malawi",
    population: 20734262,
    alias: ["MWI", "Republic of Malawi", "Nyasaland"],
  },
  {
    name: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
    population: 20426568,
    alias: ["KAZ", "Republic of Kazakhstan"],
  },
  {
    name: "Chile",
    officialName: "Republic of Chile",
    population: 20206953,
    alias: ["CHL", "Republic of Chile"],
  },
  {
    name: "Zambia",
    officialName: "Republic of Zambia",
    population: 19693423,
    alias: ["ZMB", "Republic of Zambia", "Northern Rhodesia"],
  },
  {
    name: "Somalia",
    officialName: "Federal Republic of Somalia",
    population: 19655000,
    alias: ["SOM", "Federal Republic of Somalia"],
  },
  {
    name: "Chad",
    officialName: "Republic of Chad",
    population: 19340757,
    alias: ["TCD", "Republic of Chad"],
  },
  {
    name: "Romania",
    officialName: "Romania",
    population: 19036031,
    alias: ["ROU", "România"],
  },
  {
    name: "Senegal",
    officialName: "Republic of Senegal",
    population: 18593258,
    alias: ["SEN", "Republic of Senegal"],
  },
  {
    name: "Ecuador",
    officialName: "Republic of Ecuador",
    population: 18103660,
    alias: ["ECU", "Republic of Ecuador"],
  },
  {
    name: "Netherlands",
    officialName: "Kingdom of the Netherlands",
    population: 18100436,
    alias: ["NLD", "Holland", "Kingdom of the Netherlands", "Nederland"],
  },
  {
    name: "Guatemala",
    officialName: "Republic of Guatemala",
    population: 18079810,
    alias: ["GTM", "Republic of Guatemala"],
  },
  {
    name: "Cambodia",
    officialName: "Kingdom of Cambodia",
    population: 17577760,
    alias: ["KHM", "Khmer", "Kingdom of Cambodia", "Kampuchea"],
  },
  {
    name: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
    population: 17073087,
    alias: ["ZWE", "Republic of Zimbabwe", "Rhodesia"],
  },
  {
    name: "South Sudan",
    officialName: "Republic of South Sudan",
    population: 15786898,
    alias: ["SSD", "Republic of South Sudan"],
  },
  {
    name: "Guinea",
    officialName: "Republic of Guinea",
    population: 14363931,
    alias: ["GIN", "Republic of Guinea", "Guinea-Conakry"],
  },
  {
    name: "Rwanda",
    officialName: "Republic of Rwanda",
    population: 14104969,
    alias: ["RWA", "Republic of Rwanda"],
  },
  {
    name: "Benin",
    officialName: "Republic of Benin",
    population: 13224860,
    alias: ["BEN", "Republic of Benin", "Dahomey"],
  },
  {
    name: "Burundi",
    officialName: "Republic of Burundi",
    population: 12332788,
    alias: ["BDI", "Republic of Burundi"],
  },
  {
    name: "Tunisia",
    officialName: "Tunisian Republic",
    population: 11972169,
    alias: ["TUN", "Tunisian Republic"],
  },
  {
    name: "Haiti",
    officialName: "Republic of Haiti",
    population: 11867032,
    alias: ["HTI", "Republic of Haiti"],
  },
  {
    name: "Belgium",
    officialName: "Kingdom of Belgium",
    population: 11825551,
    alias: ["BEL", "BE", "Kingdom of Belgium", "Belgique", "België"],
  },
  {
    name: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
    population: 11781559,
    alias: ["PNG", "Independent State of Papua New Guinea"],
  },
  {
    name: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
    population: 11734000,
    alias: ["JOR", "Hashemite Kingdom of Jordan"],
  },
  {
    name: "Bolivia",
    officialName: "Plurinational State of Bolivia",
    population: 11365333,
    alias: ["BOL", "Plurinational State of Bolivia"],
  },
  {
    name: "United Arab Emirates",
    officialName: "United Arab Emirates",
    population: 11294243,
    alias: ["UAE", "ARE", "Emiratos"],
  },
  {
    name: "Czechia",
    officialName: "Czech Republic",
    population: 10882341,
    alias: ["CZE", "Czech Republic", "Česká republika"],
  },
  {
    name: "Dominican Republic",
    officialName: "Dominican Republic",
    population: 10771504,
    alias: ["DOM", "República Dominicana"],
  },
  {
    name: "Portugal",
    officialName: "Portuguese Republic",
    population: 10749635,
    alias: ["PRT", "Portuguese Republic"],
  },
  {
    name: "Sweden",
    officialName: "Kingdom of Sweden",
    population: 10605098,
    alias: ["SWE", "Sverige", "Kingdom of Sweden"],
  },
  {
    name: "Tajikistan",
    officialName: "Republic of Tajikistan",
    population: 10499000,
    alias: ["TJK", "Republic of Tajikistan"],
  },
  {
    name: "Greece",
    officialName: "Hellenic Republic",
    population: 10400720,
    alias: ["GRC", "Hellenic Republic", "Hellas", "Ελλάδα"],
  },
  {
    name: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
    population: 10241722,
    alias: ["AZE", "Republic of Azerbaijan"],
  },
  {
    name: "Israel",
    officialName: "State of Israel",
    population: 10134800,
    alias: ["ISR", "State of Israel", "ישראל"],
  },
  {
    name: "Honduras",
    officialName: "Republic of Honduras",
    population: 9892632,
    alias: ["HND", "Republic of Honduras"],
  },
  {
    name: "Cuba",
    officialName: "Republic of Cuba",
    population: 9748007,
    alias: ["CUB", "Republic of Cuba"],
  },
  {
    name: "Hungary",
    officialName: "Hungary",
    population: 9539502,
    alias: ["HUN", "Magyarország"],
  },
  {
    name: "Austria",
    officialName: "Republic of Austria",
    population: 9200931,
    alias: ["AUT", "Republic of Austria", "Österreich"],
  },
  {
    name: "Belarus",
    officialName: "Republic of Belarus",
    population: 9109280,
    alias: ["BLR", "Republic of Belarus", "Byelorussia"],
  },
  {
    name: "Switzerland",
    officialName: "Swiss Confederation",
    population: 9082848,
    alias: ["CHE", "Swiss Confederation", "Schweiz", "Suisse", "Svizzera"],
  },
  {
    name: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
    population: 9077691,
    alias: ["SLE", "Republic of Sierra Leone"],
  },
  {
    name: "Togo",
    officialName: "Togolese Republic",
    population: 8095498,
    alias: ["TGO", "Togolese Republic"],
  },
  {
    name: "Laos",
    officialName: "Lao People's Democratic Republic",
    population: 7647000,
    alias: ["LAO", "Lao PDR", "Lao People's Democratic Republic"],
  },
  {
    name: "Hong Kong",
    officialName:
      "Hong Kong Special Administrative Region of the People's Republic of China",
    population: 7527500,
    alias: ["HKG", "HK", "Hong Kong SAR"],
  },
  {
    name: "Libya",
    officialName: "State of Libya",
    population: 7459000,
    alias: ["LBY", "State of Libya"],
  },
  {
    name: "Kyrgyzstan",
    officialName: "Kyrgyz Republic",
    population: 7281800,
    alias: ["KGZ", "Kyrgyz Republic", "Kirghizia"],
  },
  {
    name: "Turkmenistan",
    officialName: "Turkmenistan",
    population: 7057841,
    alias: ["TKM"],
  },
  {
    name: "Nicaragua",
    officialName: "Republic of Nicaragua",
    population: 6803886,
    alias: ["NIC", "Republic of Nicaragua"],
  },
  {
    name: "Serbia",
    officialName: "Republic of Serbia",
    population: 6567783,
    alias: ["SRB", "Republic of Serbia", "Srbija"],
  },
  {
    name: "Central African Republic",
    officialName: "Central African Republic",
    population: 6470307,
    alias: ["CAF", "CAR"],
  },
  {
    name: "Bulgaria",
    officialName: "Republic of Bulgaria",
    population: 6437360,
    alias: ["BGR", "Republic of Bulgaria", "България"],
  },
  {
    name: "Republic of the Congo",
    officialName: "Republic of the Congo",
    population: 6142180,
    alias: ["COG", "Congo-Brazzaville", "Congo Republic"],
  },
  {
    name: "Singapore",
    officialName: "Republic of Singapore",
    population: 6110200,
    alias: ["SGP", "SG", "Republic of Singapore"],
  },
  {
    name: "Paraguay",
    officialName: "Republic of Paraguay",
    population: 6109644,
    alias: ["PRY", "Republic of Paraguay"],
  },
  {
    name: "El Salvador",
    officialName: "Republic of El Salvador",
    population: 6029976,
    alias: ["SLV", "Republic of El Salvador"],
  },
  {
    name: "Denmark",
    officialName: "Kingdom of Denmark",
    population: 6011488,
    alias: ["DNK", "Danmark", "Kingdom of Denmark"],
  },
  {
    name: "Finland",
    officialName: "Republic of Finland",
    population: 5650325,
    alias: ["FIN", "Suomi", "Republic of Finland"],
  },
  {
    name: "Norway",
    officialName: "Kingdom of Norway",
    population: 5606944,
    alias: ["NOR", "Norge", "Kingdom of Norway"],
  },
  {
    name: "Lebanon",
    officialName: "Lebanese Republic",
    population: 5490000,
    alias: ["LBN", "Lebanese Republic"],
  },
  {
    name: "Palestine",
    officialName: "State of Palestine",
    population: 5483450,
    alias: [
      "PSE",
      "Palestinian Territory",
      "State of Palestine",
      "West Bank and Gaza",
    ],
  },
  {
    name: "Ireland",
    officialName: "Republic of Ireland",
    population: 5458600,
    alias: ["IRL", "Éire", "Republic of Ireland"],
  },
  {
    name: "Slovakia",
    officialName: "Slovak Republic",
    population: 5413813,
    alias: ["SVK", "Slovak Republic", "Slovensko"],
  },
  {
    name: "Oman",
    officialName: "Sultanate of Oman",
    population: 5343630,
    alias: ["OMN", "Sultanate of Oman"],
  },
  {
    name: "New Zealand",
    officialName: "New Zealand",
    population: 5324700,
    alias: ["NZL", "NZ", "Aotearoa"],
  },
  {
    name: "Costa Rica",
    officialName: "Republic of Costa Rica",
    population: 5309625,
    alias: ["CRI", "Republic of Costa Rica"],
  },
  {
    name: "Liberia",
    officialName: "Republic of Liberia",
    population: 5248621,
    alias: ["LBR", "Republic of Liberia"],
  },
  {
    name: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
    population: 4927532,
    alias: ["MRT", "Islamic Republic of Mauritania"],
  },
  {
    name: "Kuwait",
    officialName: "State of Kuwait",
    population: 4881254,
    alias: ["KWT", "State of Kuwait"],
  },
  {
    name: "Panama",
    officialName: "Republic of Panama",
    population: 4064780,
    alias: ["PAN", "Republic of Panama"],
  },
  {
    name: "Georgia",
    officialName: "Georgia",
    population: 4000921,
    alias: ["GEO", "საქართველო"],
  },
  {
    name: "Croatia",
    officialName: "Republic of Croatia",
    population: 3866233,
    alias: ["HRV", "Hrvatska", "Republic of Croatia"],
  },
  {
    name: "Eritrea",
    officialName: "State of Eritrea",
    population: 3607000,
    alias: ["ERI", "State of Eritrea"],
  },
  {
    name: "Mongolia",
    officialName: "Mongolia",
    population: 3544835,
    alias: ["MNG", "Mongol Uls"],
  },
  {
    name: "Uruguay",
    officialName: "Oriental Republic of Uruguay",
    population: 3499451,
    alias: ["URY", "Oriental Republic of Uruguay"],
  },
  {
    name: "Bosnia and Herzegovina",
    officialName: "Bosnia and Herzegovina",
    population: 3422000,
    alias: ["BIH", "BiH", "Bosnia", "Herzegovina"],
  },
  {
    name: "Puerto Rico",
    officialName: "Commonwealth of Puerto Rico",
    population: 3203295,
    alias: ["PRI", "PR", "Commonwealth of Puerto Rico"],
  },
  {
    name: "Qatar",
    officialName: "State of Qatar",
    population: 3173024,
    alias: ["QAT", "State of Qatar"],
  },
  {
    name: "Armenia",
    officialName: "Republic of Armenia",
    population: 3076200,
    alias: ["ARM", "Republic of Armenia", "Hayastan"],
  },
  {
    name: "Namibia",
    officialName: "Republic of Namibia",
    population: 3022401,
    alias: ["NAM", "Republic of Namibia", "South West Africa"],
  },
  {
    name: "Lithuania",
    officialName: "Republic of Lithuania",
    population: 2894886,
    alias: ["LTU", "Republic of Lithuania", "Lietuva"],
  },
  {
    name: "Jamaica",
    officialName: "Jamaica",
    population: 2825544,
    alias: ["JAM", "JM"],
  },
  {
    name: "Moldova",
    officialName: "Republic of Moldova",
    population: 2749076,
    alias: ["MDA", "Republic of Moldova"],
  },
  {
    name: "Gabon",
    officialName: "Gabonese Republic",
    population: 2469296,
    alias: ["GAB", "Gabonese Republic"],
  },
  {
    name: "Gambia",
    officialName: "Republic of the Gambia",
    population: 2422712,
    alias: ["GMB", "The Gambia", "Republic of the Gambia"],
  },
  {
    name: "Albania",
    officialName: "Republic of Albania",
    population: 2363314,
    alias: ["ALB", "Republic of Albania", "Shqipëria"],
  },
  {
    name: "Botswana",
    officialName: "Republic of Botswana",
    population: 2359609,
    alias: ["BWA", "Republic of Botswana", "Bechuanaland"],
  },
  {
    name: "Slovenia",
    officialName: "Republic of Slovenia",
    population: 2130638,
    alias: ["SVN", "Republic of Slovenia", "Slovenija"],
  },
  {
    name: "Lesotho",
    officialName: "Kingdom of Lesotho",
    population: 2116427,
    alias: ["LSO", "Kingdom of Lesotho", "Basutoland"],
  },
  {
    name: "Latvia",
    officialName: "Republic of Latvia",
    population: 1829000,
    alias: ["LVA", "Republic of Latvia", "Latvija"],
  },
  {
    name: "North Macedonia",
    officialName: "Republic of North Macedonia",
    population: 1822612,
    alias: ["MKD", "Republic of North Macedonia", "Macedonia", "FYROM"],
  },
  {
    name: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
    population: 1781308,
    alias: ["GNB", "Republic of Guinea-Bissau"],
  },
  {
    name: "Equatorial Guinea",
    officialName: "Republic of Equatorial Guinea",
    population: 1668768,
    alias: ["GNQ", "Republic of Equatorial Guinea"],
  },
  {
    name: "Bahrain",
    officialName: "Kingdom of Bahrain",
    population: 1594654,
    alias: ["BHR", "Kingdom of Bahrain"],
  },
  {
    name: "Kosovo",
    officialName: "Republic of Kosovo",
    population: 1585566,
    alias: ["XKX", "Republic of Kosovo", "Kosovë"],
  },
  {
    name: "Cyprus",
    officialName: "Republic of Cyprus",
    population: 1442614,
    alias: ["CYP", "Republic of Cyprus", "Kypros"],
  },
  {
    name: "Timor-Leste",
    officialName: "Democratic Republic of Timor-Leste",
    population: 1391221,
    alias: ["TLS", "East Timor", "Democratic Republic of Timor-Leste"],
  },
  {
    name: "Estonia",
    officialName: "Republic of Estonia",
    population: 1369995,
    alias: ["EST", "Republic of Estonia", "Eesti"],
  },
  {
    name: "Trinidad and Tobago",
    officialName: "Republic of Trinidad and Tobago",
    population: 1367764,
    alias: ["TTO", "T&T", "Republic of Trinidad and Tobago"],
  },
  {
    name: "Mauritius",
    officialName: "Republic of Mauritius",
    population: 1243741,
    alias: ["MUS", "Republic of Mauritius"],
  },
  {
    name: "Eswatini",
    officialName: "Kingdom of Eswatini",
    population: 1235549,
    alias: ["SWZ", "Kingdom of Eswatini", "Swaziland"],
  },
  {
    name: "Djibouti",
    officialName: "Republic of Djibouti",
    population: 1066809,
    alias: ["DJI", "Republic of Djibouti"],
  },
  {
    name: "Comoros",
    officialName: "Union of the Comoros",
    population: 919901,
    alias: ["COM", "Union of the Comoros"],
  },
  {
    name: "Fiji",
    officialName: "Republic of Fiji",
    population: 900869,
    alias: ["FJI", "Republic of Fiji"],
  },
  {
    name: "Réunion",
    officialName: "Réunion Island",
    population: 896175,
    alias: ["REU", "Reunion"],
  },
  {
    name: "Bhutan",
    officialName: "Kingdom of Bhutan",
    population: 784043,
    alias: ["BTN", "Kingdom of Bhutan", "Druk Yul"],
  },
  {
    name: "Guyana",
    officialName: "Co-operative Republic of Guyana",
    population: 772975,
    alias: ["GUY", "Co-operative Republic of Guyana", "British Guiana"],
  },
  {
    name: "Solomon Islands",
    officialName: "Solomon Islands",
    population: 750325,
    alias: ["SLB", "Solomon Islands"],
  },
  {
    name: "Macau",
    officialName:
      "Macao Special Administrative Region of the People's Republic of China",
    population: 685900,
    alias: ["MAC", "Macao", "Macau SAR"],
  },
  {
    name: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
    population: 681973,
    alias: ["LUX", "Grand Duchy of Luxembourg", "Lëtzebuerg"],
  },
  {
    name: "Montenegro",
    officialName: "Montenegro",
    population: 623327,
    alias: ["MNE", "Crna Gora"],
  },
  {
    name: "Suriname",
    officialName: "Republic of Suriname",
    population: 616500,
    alias: ["SUR", "Republic of Suriname", "Dutch Guiana"],
  },
  {
    name: "Western Sahara",
    officialName: "Sahrawi Arab Democratic Republic",
    population: 600904,
    alias: ["ESH", "SADR", "Sahrawi Arab Democratic Republic"],
  },
  {
    name: "Malta",
    officialName: "Republic of Malta",
    population: 574250,
    alias: ["MLT", "Republic of Malta"],
  },
  {
    name: "Maldives",
    officialName: "Republic of the Maldives",
    population: 515132,
    alias: ["MDV", "Republic of the Maldives"],
  },
  {
    name: "Cape Verde",
    officialName: "Republic of Cabo Verde",
    population: 491233,
    alias: ["CPV", "Cabo Verde", "Republic of Cabo Verde"],
  },
  {
    name: "Brunei",
    officialName: "Nation of Brunei, Abode of Peace",
    population: 455500,
    alias: ["BRN", "Brunei Darussalam", "Nation of Brunei, Abode of Peace"],
  },
  {
    name: "Belize",
    officialName: "Belize",
    population: 417634,
    alias: ["BLZ", "British Honduras"],
  },
  {
    name: "Bahamas",
    officialName: "Commonwealth of the Bahamas",
    population: 398165,
    alias: ["BHS", "The Bahamas", "Commonwealth of the Bahamas"],
  },
  {
    name: "Iceland",
    officialName: "Iceland",
    population: 391810,
    alias: ["ISL", "Ísland"],
  },
  {
    name: "Guadeloupe",
    officialName: "Guadeloupe",
    population: 378561,
    alias: ["GLP"],
  },
  {
    name: "Martinique",
    officialName: "Martinique",
    population: 349925,
    alias: ["MTQ"],
  },
  {
    name: "Vanuatu",
    officialName: "Republic of Vanuatu",
    population: 321409,
    alias: ["VUT", "Republic of Vanuatu", "New Hebrides"],
  },
  {
    name: "Mayotte",
    officialName: "Department of Mayotte",
    population: 320901,
    alias: ["MYT", "Department of Mayotte"],
  },
  {
    name: "French Guiana",
    officialName: "Guiana",
    population: 292354,
    alias: ["GUF", "Guyane"],
  },
  {
    name: "French Polynesia",
    officialName: "French Polynesia",
    population: 279500,
    alias: ["PYF", "Tahiti"],
  },
  {
    name: "Barbados",
    officialName: "Barbados",
    population: 267800,
    alias: ["BRB"],
  },
  {
    name: "New Caledonia",
    officialName: "New Caledonia",
    population: 264596,
    alias: ["NCL", "Nouvelle-Calédonie"],
  },
  {
    name: "São Tomé and Príncipe",
    officialName: "Democratic Republic of São Tomé and Príncipe",
    population: 209607,
    alias: ["STP", "Sao Tome and Principe"],
  },
  {
    name: "Samoa",
    officialName: "Independent State of Samoa",
    population: 205557,
    alias: ["WSM", "Independent State of Samoa", "Western Samoa"],
  },
  {
    name: "Saint Lucia",
    officialName: "Saint Lucia",
    population: 184100,
    alias: ["LCA", "St. Lucia"],
  },
  {
    name: "Curaçao",
    officialName: "Country of Curaçao",
    population: 156115,
    alias: ["CUW", "Curacao"],
  },
  { name: "Guam", officialName: "Guam", population: 153836, alias: ["GUM"] },
  {
    name: "Seychelles",
    officialName: "Republic of Seychelles",
    population: 122729,
    alias: ["SYC", "Republic of Seychelles"],
  },
  {
    name: "Kiribati",
    officialName: "Independent and Sovereign Republic of Kiribati",
    population: 120740,
    alias: ["KIR", "Independent and Sovereign Republic of Kiribati"],
  },
  {
    name: "Saint Vincent and the Grenadines",
    officialName: "Saint Vincent and the Grenadines",
    population: 110872,
    alias: ["VCT", "SVG", "St. Vincent"],
  },
  {
    name: "Grenada",
    officialName: "Grenada",
    population: 109021,
    alias: ["GRD"],
  },
  { name: "Aruba", officialName: "Aruba", population: 107566, alias: ["ABW"] },
  {
    name: "Micronesia",
    officialName: "Federated States of Micronesia",
    population: 105564,
    alias: ["FSM", "Federated States of Micronesia"],
  },
  {
    name: "Antigua and Barbuda",
    officialName: "Antigua and Barbuda",
    population: 103603,
    alias: ["ATG", "Antigua"],
  },
  {
    name: "Jersey",
    officialName: "Bailiwick of Jersey",
    population: 103267,
    alias: ["JEY", "Bailiwick of Jersey"],
  },
  {
    name: "Tonga",
    officialName: "Kingdom of Tonga",
    population: 100179,
    alias: ["TON", "Kingdom of Tonga"],
  },
  {
    name: "Andorra",
    officialName: "Principality of Andorra",
    population: 88406,
    alias: ["AND", "Principality of Andorra"],
  },
  {
    name: "United States Virgin Islands",
    officialName: "Virgin Islands of the United States",
    population: 87146,
    alias: ["VIR", "USVI", "US Virgin Islands"],
  },
  {
    name: "Cayman Islands",
    officialName: "Cayman Islands",
    population: 84738,
    alias: ["CYM"],
  },
  {
    name: "Isle of Man",
    officialName: "Isle of Man",
    population: 84530,
    alias: ["IMN", "IOM"],
  },
  {
    name: "Dominica",
    officialName: "Commonwealth of Dominica",
    population: 67408,
    alias: ["DMA", "Commonwealth of Dominica"],
  },
  {
    name: "Guernsey",
    officialName: "Bailiwick of Guernsey",
    population: 64781,
    alias: ["GGY", "Bailiwick of Guernsey"],
  },
  {
    name: "Bermuda",
    officialName: "Bermuda",
    population: 64055,
    alias: ["BMU"],
  },
  {
    name: "Greenland",
    officialName: "Greenland",
    population: 56542,
    alias: ["GRL", "Kalaallit Nunaat"],
  },
  {
    name: "Faroe Islands",
    officialName: "Faroe Islands",
    population: 54885,
    alias: ["FRO", "Føroyar"],
  },
  {
    name: "Saint Kitts and Nevis",
    officialName: "Federation of Saint Christopher and Nevis",
    population: 51320,
    alias: ["KNA", "St. Kitts and Nevis", "St. Kitts"],
  },
  {
    name: "Turks and Caicos Islands",
    officialName: "Turks and Caicos Islands",
    population: 50828,
    alias: ["TCA", "TCI"],
  },
  {
    name: "American Samoa",
    officialName: "American Samoa",
    population: 49710,
    alias: ["ASM"],
  },
  {
    name: "Northern Mariana Islands",
    officialName: "Commonwealth of the Northern Mariana Islands",
    population: 47329,
    alias: ["MNP", "CNMI"],
  },
  {
    name: "Marshall Islands",
    officialName: "Republic of the Marshall Islands",
    population: 42418,
    alias: ["MHL", "Republic of the Marshall Islands"],
  },
  {
    name: "Sint Maarten",
    officialName: "Sint Maarten",
    population: 41349,
    alias: ["SXM", "Saint Maarten"],
  },
  {
    name: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
    population: 40900,
    alias: ["LIE", "Principality of Liechtenstein"],
  },
  {
    name: "British Virgin Islands",
    officialName: "Virgin Islands",
    population: 39471,
    alias: ["VGB", "BVI"],
  },
  {
    name: "Monaco",
    officialName: "Principality of Monaco",
    population: 38423,
    alias: ["MCO", "Principality of Monaco"],
  },
  {
    name: "Gibraltar",
    officialName: "Gibraltar",
    population: 38000,
    alias: ["GIB", "The Rock"],
  },
  {
    name: "San Marino",
    officialName: "Republic of San Marino",
    population: 34132,
    alias: ["SMR", "Republic of San Marino"],
  },
  {
    name: "Caribbean Netherlands",
    officialName: "Bonaire, Sint Eustatius and Saba",
    population: 31980,
    alias: ["BES", "Bonaire", "Sint Eustatius", "Saba"],
  },
  {
    name: "Saint Martin",
    officialName: "Saint Martin",
    population: 31496,
    alias: ["MAF", "St. Martin"],
  },
  {
    name: "Åland Islands",
    officialName: "Åland Islands",
    population: 30654,
    alias: ["ALA", "Aland Islands"],
  },
  {
    name: "Palau",
    officialName: "Republic of Palau",
    population: 16733,
    alias: ["PLW", "Republic of Palau"],
  },
  {
    name: "Anguilla",
    officialName: "Anguilla",
    population: 16010,
    alias: ["AIA"],
  },
  {
    name: "Cook Islands",
    officialName: "Cook Islands",
    population: 15040,
    alias: ["COK"],
  },
  {
    name: "Nauru",
    officialName: "Republic of Nauru",
    population: 11680,
    alias: ["NRU", "Republic of Nauru"],
  },
  {
    name: "Wallis and Futuna",
    officialName: "Territory of the Wallis and Futuna Islands",
    population: 11620,
    alias: ["WLF", "Territory of the Wallis and Futuna Islands"],
  },
  { name: "Tuvalu", officialName: "Tuvalu", population: 10643, alias: ["TUV"] },
  {
    name: "Saint Barthélemy",
    officialName: "Collectivity of Saint Barthélemy",
    population: 10562,
    alias: ["BLM", "St. Barths", "St. Barts"],
  },
  {
    name: "Saint Pierre and Miquelon",
    officialName: "Saint Pierre and Miquelon",
    population: 5819,
    alias: ["SPM", "St. Pierre and Miquelon"],
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    officialName: "Saint Helena, Ascension and Tristan da Cunha",
    population: 5651,
    alias: ["SHN", "St. Helena"],
  },
  {
    name: "Montserrat",
    officialName: "Montserrat",
    population: 4386,
    alias: ["MSR", "Emerald Isle of the Caribbean"],
  },
  {
    name: "Falkland Islands",
    officialName: "Falkland Islands",
    population: 3662,
    alias: ["FLK", "Malvinas", "Islas Malvinas"],
  },
  {
    name: "Tokelau",
    officialName: "Tokelau",
    population: 2608,
    alias: ["TKL"],
  },
  {
    name: "Svalbard and Jan Mayen",
    officialName: "Svalbard og Jan Mayen",
    population: 2530,
    alias: ["SJM", "Svalbard"],
  },
  {
    name: "Norfolk Island",
    officialName: "Territory of Norfolk Island",
    population: 2188,
    alias: ["NFK", "Territory of Norfolk Island"],
  },
  {
    name: "Christmas Island",
    officialName: "Territory of Christmas Island",
    population: 1692,
    alias: ["CXR", "Territory of Christmas Island"],
  },
  { name: "Niue", officialName: "Niue", population: 1681, alias: ["NIU"] },
  {
    name: "Antarctica",
    officialName: "Antarctica",
    population: 1300,
    alias: ["ATA", "Antarctic"],
  },
  {
    name: "Vatican City",
    officialName: "Vatican City State",
    population: 882,
    alias: ["VAT", "Holy See", "Vatican City State"],
  },
  {
    name: "Cocos (Keeling) Islands",
    officialName: "Territory of the Cocos (Keeling) Islands",
    population: 593,
    alias: ["CCK", "Keeling Islands"],
  },
  {
    name: "French Southern and Antarctic Lands",
    officialName: "Territory of the French Southern and Antarctic Lands",
    population: 400,
    alias: ["ATF", "TAAF"],
  },
  {
    name: "Pitcairn Islands",
    officialName: "Pitcairn Group of Islands",
    population: 35,
    alias: ["PCN", "Pitcairn Group of Islands"],
  },
];
