import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  { name: "India", officialName: "Republic of India", population: 1417492000 },
  {
    name: "China",
    officialName: "People's Republic of China",
    population: 1408280000,
  },
  {
    name: "United States",
    officialName: "United States of America",
    population: 340110988,
  },
  {
    name: "Indonesia",
    officialName: "Republic of Indonesia",
    population: 284438782,
  },
  {
    name: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
    population: 241499431,
  },
  {
    name: "Nigeria",
    officialName: "Federal Republic of Nigeria",
    population: 223800000,
  },
  {
    name: "Brazil",
    officialName: "Federative Republic of Brazil",
    population: 213421037,
  },
  {
    name: "Bangladesh",
    officialName: "People's Republic of Bangladesh",
    population: 169828911,
  },
  { name: "Russia", officialName: "Russian Federation", population: 146028325 },
  {
    name: "Mexico",
    officialName: "United Mexican States",
    population: 130575786,
  },
  { name: "Japan", officialName: "Japan", population: 123210000 },
  {
    name: "Philippines",
    officialName: "Republic of the Philippines",
    population: 114123600,
  },
  {
    name: "DR Congo",
    officialName: "Democratic Republic of the Congo",
    population: 112832000,
  },
  {
    name: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
    population: 111652998,
  },
  {
    name: "Egypt",
    officialName: "Arab Republic of Egypt",
    population: 107271260,
  },
  {
    name: "Vietnam",
    officialName: "Socialist Republic of Vietnam",
    population: 101343800,
  },
  {
    name: "Iran",
    officialName: "Islamic Republic of Iran",
    population: 85961000,
  },
  { name: "Turkey", officialName: "Republic of Turkey", population: 85664944 },
  {
    name: "Germany",
    officialName: "Federal Republic of Germany",
    population: 83491249,
  },
  {
    name: "United Kingdom",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
    population: 69281437,
  },
  {
    name: "Tanzania",
    officialName: "United Republic of Tanzania",
    population: 68153004,
  },
  { name: "France", officialName: "French Republic", population: 66351959 },
  {
    name: "Thailand",
    officialName: "Kingdom of Thailand",
    population: 65859640,
  },
  {
    name: "South Africa",
    officialName: "Republic of South Africa",
    population: 63100945,
  },
  { name: "Italy", officialName: "Italian Republic", population: 58927633 },
  { name: "Kenya", officialName: "Republic of Kenya", population: 53330978 },
  {
    name: "Colombia",
    officialName: "Republic of Colombia",
    population: 53057212,
  },
  {
    name: "Sudan",
    officialName: "Republic of the Sudan",
    population: 51662000,
  },
  {
    name: "Myanmar",
    officialName: "Republic of the Union of Myanmar",
    population: 51316756,
  },
  {
    name: "South Korea",
    officialName: "Republic of Korea",
    population: 51159889,
  },
  { name: "Spain", officialName: "Kingdom of Spain", population: 49315949 },
  {
    name: "Algeria",
    officialName: "People's Democratic Republic of Algeria",
    population: 47400000,
  },
  {
    name: "Argentina",
    officialName: "Argentine Republic",
    population: 46735004,
  },
  { name: "Iraq", officialName: "Republic of Iraq", population: 46118793 },
  { name: "Uganda", officialName: "Republic of Uganda", population: 45905417 },
  {
    name: "Afghanistan",
    officialName: "Islamic Republic of Afghanistan",
    population: 43844000,
  },
  { name: "Canada", officialName: "Canada", population: 41651653 },
  {
    name: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
    population: 37859698,
  },
  { name: "Poland", officialName: "Republic of Poland", population: 37392000 },
  { name: "Morocco", officialName: "Kingdom of Morocco", population: 36828330 },
  { name: "Angola", officialName: "Republic of Angola", population: 36170961 },
  {
    name: "Saudi Arabia",
    officialName: "Kingdom of Saudi Arabia",
    population: 35300280,
  },
  { name: "Peru", officialName: "Republic of Peru", population: 34350244 },
  { name: "Malaysia", officialName: "Malaysia", population: 34231700 },
  {
    name: "Mozambique",
    officialName: "Republic of Mozambique",
    population: 34090466,
  },
  { name: "Ghana", officialName: "Republic of Ghana", population: 33742380 },
  { name: "Ukraine", officialName: "Ukraine", population: 32862000 },
  { name: "Yemen", officialName: "Republic of Yemen", population: 32684503 },
  {
    name: "Madagascar",
    officialName: "Republic of Madagascar",
    population: 31727042,
  },
  {
    name: "Ivory Coast",
    officialName: "Republic of Côte d'Ivoire",
    population: 31719275,
  },
  {
    name: "Nepal",
    officialName: "Federal Democratic Republic of Nepal",
    population: 29911840,
  },
  {
    name: "Cameroon",
    officialName: "Republic of Cameroon",
    population: 29442327,
  },
  {
    name: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
    population: 28517000,
  },
  {
    name: "Australia",
    officialName: "Commonwealth of Australia",
    population: 27536874,
  },
  { name: "Niger", officialName: "Republic of Niger", population: 26312034 },
  {
    name: "North Korea",
    officialName: "Democratic People's Republic of Korea",
    population: 25950000,
  },
  { name: "Syria", officialName: "Syrian Arab Republic", population: 25620000 },
  { name: "Burkina Faso", officialName: "Burkina Faso", population: 24070553 },
  {
    name: "Taiwan",
    officialName: "Republic of China (Taiwan)",
    population: 23317031,
  },
  { name: "Mali", officialName: "Republic of Mali", population: 22395489 },
  {
    name: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
    population: 21763170,
  },
  { name: "Malawi", officialName: "Republic of Malawi", population: 20734262 },
  {
    name: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
    population: 20426568,
  },
  { name: "Chile", officialName: "Republic of Chile", population: 20206953 },
  { name: "Zambia", officialName: "Republic of Zambia", population: 19693423 },
  {
    name: "Somalia",
    officialName: "Federal Republic of Somalia",
    population: 19655000,
  },
  { name: "Chad", officialName: "Republic of Chad", population: 19340757 },
  { name: "Romania", officialName: "Romania", population: 19036031 },
  {
    name: "Senegal",
    officialName: "Republic of Senegal",
    population: 18593258,
  },
  {
    name: "Ecuador",
    officialName: "Republic of Ecuador",
    population: 18103660,
  },
  {
    name: "Netherlands",
    officialName: "Kingdom of the Netherlands",
    population: 18100436,
  },
  {
    name: "Guatemala",
    officialName: "Republic of Guatemala",
    population: 18079810,
  },
  {
    name: "Cambodia",
    officialName: "Kingdom of Cambodia",
    population: 17577760,
  },
  {
    name: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
    population: 17073087,
  },
  {
    name: "South Sudan",
    officialName: "Republic of South Sudan",
    population: 15786898,
  },
  { name: "Guinea", officialName: "Republic of Guinea", population: 14363931 },
  { name: "Rwanda", officialName: "Republic of Rwanda", population: 14104969 },
  { name: "Benin", officialName: "Republic of Benin", population: 13224860 },
  {
    name: "Burundi",
    officialName: "Republic of Burundi",
    population: 12332788,
  },
  { name: "Tunisia", officialName: "Tunisian Republic", population: 11972169 },
  { name: "Haiti", officialName: "Republic of Haiti", population: 11867032 },
  { name: "Belgium", officialName: "Kingdom of Belgium", population: 11825551 },
  {
    name: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
    population: 11781559,
  },
  {
    name: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
    population: 11734000,
  },
  {
    name: "Bolivia",
    officialName: "Plurinational State of Bolivia",
    population: 11365333,
  },
  {
    name: "United Arab Emirates",
    officialName: "United Arab Emirates",
    population: 11294243,
  },
  { name: "Czechia", officialName: "Czech Republic", population: 10882341 },
  {
    name: "Dominican Republic",
    officialName: "Dominican Republic",
    population: 10771504,
  },
  {
    name: "Portugal",
    officialName: "Portuguese Republic",
    population: 10749635,
  },
  { name: "Sweden", officialName: "Kingdom of Sweden", population: 10605098 },
  {
    name: "Tajikistan",
    officialName: "Republic of Tajikistan",
    population: 10499000,
  },
  { name: "Greece", officialName: "Hellenic Republic", population: 10400720 },
  {
    name: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
    population: 10241722,
  },
  { name: "Israel", officialName: "State of Israel", population: 10134800 },
  {
    name: "Honduras",
    officialName: "Republic of Honduras",
    population: 9892632,
  },
  { name: "Cuba", officialName: "Republic of Cuba", population: 9748007 },
  { name: "Hungary", officialName: "Hungary", population: 9539502 },
  { name: "Austria", officialName: "Republic of Austria", population: 9200931 },
  { name: "Belarus", officialName: "Republic of Belarus", population: 9109280 },
  {
    name: "Switzerland",
    officialName: "Swiss Confederation",
    population: 9082848,
  },
  {
    name: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
    population: 9077691,
  },
  { name: "Togo", officialName: "Togolese Republic", population: 8095498 },
  {
    name: "Laos",
    officialName: "Lao People's Democratic Republic",
    population: 7647000,
  },
  {
    name: "Hong Kong",
    officialName:
      "Hong Kong Special Administrative Region of the People's Republic of China",
    population: 7527500,
  },
  { name: "Libya", officialName: "State of Libya", population: 7459000 },
  { name: "Kyrgyzstan", officialName: "Kyrgyz Republic", population: 7281800 },
  { name: "Turkmenistan", officialName: "Turkmenistan", population: 7057841 },
  {
    name: "Nicaragua",
    officialName: "Republic of Nicaragua",
    population: 6803886,
  },
  { name: "Serbia", officialName: "Republic of Serbia", population: 6567783 },
  {
    name: "Central African Republic",
    officialName: "Central African Republic",
    population: 6470307,
  },
  {
    name: "Bulgaria",
    officialName: "Republic of Bulgaria",
    population: 6437360,
  },
  {
    name: "Republic of the Congo",
    officialName: "Republic of the Congo",
    population: 6142180,
  },
  {
    name: "Singapore",
    officialName: "Republic of Singapore",
    population: 6110200,
  },
  {
    name: "Paraguay",
    officialName: "Republic of Paraguay",
    population: 6109644,
  },
  {
    name: "El Salvador",
    officialName: "Republic of El Salvador",
    population: 6029976,
  },
  { name: "Denmark", officialName: "Kingdom of Denmark", population: 6011488 },
  { name: "Finland", officialName: "Republic of Finland", population: 5650325 },
  { name: "Norway", officialName: "Kingdom of Norway", population: 5606944 },
  { name: "Lebanon", officialName: "Lebanese Republic", population: 5490000 },
  {
    name: "Palestine",
    officialName: "State of Palestine",
    population: 5483450,
  },
  { name: "Ireland", officialName: "Republic of Ireland", population: 5458600 },
  { name: "Slovakia", officialName: "Slovak Republic", population: 5413813 },
  { name: "Oman", officialName: "Sultanate of Oman", population: 5343630 },
  { name: "New Zealand", officialName: "New Zealand", population: 5324700 },
  {
    name: "Costa Rica",
    officialName: "Republic of Costa Rica",
    population: 5309625,
  },
  { name: "Liberia", officialName: "Republic of Liberia", population: 5248621 },
  {
    name: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
    population: 4927532,
  },
  { name: "Kuwait", officialName: "State of Kuwait", population: 4881254 },
  { name: "Panama", officialName: "Republic of Panama", population: 4064780 },
  { name: "Georgia", officialName: "Georgia", population: 4000921 },
  { name: "Croatia", officialName: "Republic of Croatia", population: 3866233 },
  { name: "Eritrea", officialName: "State of Eritrea", population: 3607000 },
  { name: "Mongolia", officialName: "Mongolia", population: 3544835 },
  {
    name: "Uruguay",
    officialName: "Oriental Republic of Uruguay",
    population: 3499451,
  },
  {
    name: "Bosnia and Herzegovina",
    officialName: "Bosnia and Herzegovina",
    population: 3422000,
  },
  {
    name: "Puerto Rico",
    officialName: "Commonwealth of Puerto Rico",
    population: 3203295,
  },
  { name: "Qatar", officialName: "State of Qatar", population: 3173024 },
  { name: "Armenia", officialName: "Republic of Armenia", population: 3076200 },
  { name: "Namibia", officialName: "Republic of Namibia", population: 3022401 },
  {
    name: "Lithuania",
    officialName: "Republic of Lithuania",
    population: 2894886,
  },
  { name: "Jamaica", officialName: "Jamaica", population: 2825544 },
  { name: "Moldova", officialName: "Republic of Moldova", population: 2749076 },
  { name: "Gabon", officialName: "Gabonese Republic", population: 2469296 },
  {
    name: "Gambia",
    officialName: "Republic of the Gambia",
    population: 2422712,
  },
  { name: "Albania", officialName: "Republic of Albania", population: 2363314 },
  {
    name: "Botswana",
    officialName: "Republic of Botswana",
    population: 2359609,
  },
  {
    name: "Slovenia",
    officialName: "Republic of Slovenia",
    population: 2130638,
  },
  { name: "Lesotho", officialName: "Kingdom of Lesotho", population: 2116427 },
  { name: "Latvia", officialName: "Republic of Latvia", population: 1829000 },
  {
    name: "North Macedonia",
    officialName: "Republic of North Macedonia",
    population: 1822612,
  },
  {
    name: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
    population: 1781308,
  },
  {
    name: "Equatorial Guinea",
    officialName: "Republic of Equatorial Guinea",
    population: 1668768,
  },
  { name: "Bahrain", officialName: "Kingdom of Bahrain", population: 1594654 },
  { name: "Kosovo", officialName: "Republic of Kosovo", population: 1585566 },
  { name: "Cyprus", officialName: "Republic of Cyprus", population: 1442614 },
  {
    name: "Timor-Leste",
    officialName: "Democratic Republic of Timor-Leste",
    population: 1391221,
  },
  { name: "Estonia", officialName: "Republic of Estonia", population: 1369995 },
  {
    name: "Trinidad and Tobago",
    officialName: "Republic of Trinidad and Tobago",
    population: 1367764,
  },
  {
    name: "Mauritius",
    officialName: "Republic of Mauritius",
    population: 1243741,
  },
  {
    name: "Eswatini",
    officialName: "Kingdom of Eswatini",
    population: 1235549,
  },
  {
    name: "Djibouti",
    officialName: "Republic of Djibouti",
    population: 1066809,
  },
  { name: "Comoros", officialName: "Union of the Comoros", population: 919901 },
  { name: "Fiji", officialName: "Republic of Fiji", population: 900869 },
  { name: "Réunion", officialName: "Réunion Island", population: 896175 },
  { name: "Bhutan", officialName: "Kingdom of Bhutan", population: 784043 },
  {
    name: "Guyana",
    officialName: "Co-operative Republic of Guyana",
    population: 772975,
  },
  {
    name: "Solomon Islands",
    officialName: "Solomon Islands",
    population: 750325,
  },
  {
    name: "Macau",
    officialName:
      "Macao Special Administrative Region of the People's Republic of China",
    population: 685900,
  },
  {
    name: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
    population: 681973,
  },
  { name: "Montenegro", officialName: "Montenegro", population: 623327 },
  {
    name: "Suriname",
    officialName: "Republic of Suriname",
    population: 616500,
  },
  {
    name: "Western Sahara",
    officialName: "Sahrawi Arab Democratic Republic",
    population: 600904,
  },
  { name: "Malta", officialName: "Republic of Malta", population: 574250 },
  {
    name: "Maldives",
    officialName: "Republic of the Maldives",
    population: 515132,
  },
  {
    name: "Cape Verde",
    officialName: "Republic of Cabo Verde",
    population: 491233,
  },
  {
    name: "Brunei",
    officialName: "Nation of Brunei, Abode of Peace",
    population: 455500,
  },
  { name: "Belize", officialName: "Belize", population: 417634 },
  {
    name: "Bahamas",
    officialName: "Commonwealth of the Bahamas",
    population: 398165,
  },
  { name: "Iceland", officialName: "Iceland", population: 391810 },
  { name: "Guadeloupe", officialName: "Guadeloupe", population: 378561 },
  { name: "Martinique", officialName: "Martinique", population: 349925 },
  { name: "Vanuatu", officialName: "Republic of Vanuatu", population: 321409 },
  {
    name: "Mayotte",
    officialName: "Department of Mayotte",
    population: 320901,
  },
  { name: "French Guiana", officialName: "Guiana", population: 292354 },
  {
    name: "French Polynesia",
    officialName: "French Polynesia",
    population: 279500,
  },
  { name: "Barbados", officialName: "Barbados", population: 267800 },
  { name: "New Caledonia", officialName: "New Caledonia", population: 264596 },
  {
    name: "São Tomé and Príncipe",
    officialName: "Democratic Republic of São Tomé and Príncipe",
    population: 209607,
  },
  {
    name: "Samoa",
    officialName: "Independent State of Samoa",
    population: 205557,
  },
  { name: "Saint Lucia", officialName: "Saint Lucia", population: 184100 },
  { name: "Curaçao", officialName: "Country of Curaçao", population: 156115 },
  { name: "Guam", officialName: "Guam", population: 153836 },
  {
    name: "Seychelles",
    officialName: "Republic of Seychelles",
    population: 122729,
  },
  {
    name: "Kiribati",
    officialName: "Independent and Sovereign Republic of Kiribati",
    population: 120740,
  },
  {
    name: "Saint Vincent and the Grenadines",
    officialName: "Saint Vincent and the Grenadines",
    population: 110872,
  },
  { name: "Grenada", officialName: "Grenada", population: 109021 },
  { name: "Aruba", officialName: "Aruba", population: 107566 },
  {
    name: "Micronesia",
    officialName: "Federated States of Micronesia",
    population: 105564,
  },
  {
    name: "Antigua and Barbuda",
    officialName: "Antigua and Barbuda",
    population: 103603,
  },
  { name: "Jersey", officialName: "Bailiwick of Jersey", population: 103267 },
  { name: "Tonga", officialName: "Kingdom of Tonga", population: 100179 },
  {
    name: "Andorra",
    officialName: "Principality of Andorra",
    population: 88406,
  },
  {
    name: "United States Virgin Islands",
    officialName: "Virgin Islands of the United States",
    population: 87146,
  },
  { name: "Cayman Islands", officialName: "Cayman Islands", population: 84738 },
  { name: "Isle of Man", officialName: "Isle of Man", population: 84530 },
  {
    name: "Dominica",
    officialName: "Commonwealth of Dominica",
    population: 67408,
  },
  {
    name: "Guernsey",
    officialName: "Bailiwick of Guernsey",
    population: 64781,
  },
  { name: "Bermuda", officialName: "Bermuda", population: 64055 },
  { name: "Greenland", officialName: "Greenland", population: 56542 },
  { name: "Faroe Islands", officialName: "Faroe Islands", population: 54885 },
  {
    name: "Saint Kitts and Nevis",
    officialName: "Federation of Saint Christopher and Nevis",
    population: 51320,
  },
  {
    name: "Turks and Caicos Islands",
    officialName: "Turks and Caicos Islands",
    population: 50828,
  },
  { name: "American Samoa", officialName: "American Samoa", population: 49710 },
  {
    name: "Northern Mariana Islands",
    officialName: "Commonwealth of the Northern Mariana Islands",
    population: 47329,
  },
  {
    name: "Marshall Islands",
    officialName: "Republic of the Marshall Islands",
    population: 42418,
  },
  { name: "Sint Maarten", officialName: "Sint Maarten", population: 41349 },
  {
    name: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
    population: 40900,
  },
  {
    name: "British Virgin Islands",
    officialName: "Virgin Islands",
    population: 39471,
  },
  { name: "Monaco", officialName: "Principality of Monaco", population: 38423 },
  { name: "Gibraltar", officialName: "Gibraltar", population: 38000 },
  {
    name: "San Marino",
    officialName: "Republic of San Marino",
    population: 34132,
  },
  {
    name: "Caribbean Netherlands",
    officialName: "Bonaire, Sint Eustatius and Saba",
    population: 31980,
  },
  { name: "Saint Martin", officialName: "Saint Martin", population: 31496 },
  { name: "Åland Islands", officialName: "Åland Islands", population: 30654 },
  { name: "Palau", officialName: "Republic of Palau", population: 16733 },
  { name: "Anguilla", officialName: "Anguilla", population: 16010 },
  { name: "Cook Islands", officialName: "Cook Islands", population: 15040 },
  { name: "Nauru", officialName: "Republic of Nauru", population: 11680 },
  {
    name: "Wallis and Futuna",
    officialName: "Territory of the Wallis and Futuna Islands",
    population: 11620,
  },
  { name: "Tuvalu", officialName: "Tuvalu", population: 10643 },
  {
    name: "Saint Barthélemy",
    officialName: "Collectivity of Saint Barthélemy",
    population: 10562,
  },
  {
    name: "Saint Pierre and Miquelon",
    officialName: "Saint Pierre and Miquelon",
    population: 5819,
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    officialName: "Saint Helena, Ascension and Tristan da Cunha",
    population: 5651,
  },
  { name: "Montserrat", officialName: "Montserrat", population: 4386 },
  {
    name: "Falkland Islands",
    officialName: "Falkland Islands",
    population: 3662,
  },
  { name: "Tokelau", officialName: "Tokelau", population: 2608 },
  {
    name: "Svalbard and Jan Mayen",
    officialName: "Svalbard og Jan Mayen",
    population: 2530,
  },
  {
    name: "Norfolk Island",
    officialName: "Territory of Norfolk Island",
    population: 2188,
  },
  {
    name: "Christmas Island",
    officialName: "Territory of Christmas Island",
    population: 1692,
  },
  { name: "Niue", officialName: "Niue", population: 1681 },
  { name: "Antarctica", officialName: "Antarctica", population: 1300 },
  { name: "Vatican City", officialName: "Vatican City State", population: 882 },
  {
    name: "Cocos (Keeling) Islands",
    officialName: "Territory of the Cocos (Keeling) Islands",
    population: 593,
  },
  {
    name: "French Southern and Antarctic Lands",
    officialName: "Territory of the French Southern and Antarctic Lands",
    population: 400,
  },
  {
    name: "Pitcairn Islands",
    officialName: "Pitcairn Group of Islands",
    population: 35,
  },
];
